[package]
name = "asistente-de-visitas"
version = "1.0.33"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[lib]
name = "asistente_de_visitas_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
# --- Core de Tauri ---
tauri = { version = "2", features = [] }

# --- Serialización (VITAL para tu nueva Agenda) ---
# El feature "derive" es lo que permite guardar tus structs en la BD/JSON
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# --- Base de Datos en Rust Puro ---
rusqlite = { version = "0.31.0", features = ["bundled"] }

# --- Plugins de Tauri ---
# Mantengo tus versiones actuales para asegurar estabilidad
tauri-plugin-opener = "2"
tauri-plugin-store = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2.3.3"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }

# --- Utilidades Extras (Backups/PDFs) ---
zip = "7.0.0"
flate2 = "1.1.5"

# --- Conexión a Google Drive (Sincronización) ---
yup-oauth2 = "8.3"
google-drive3 = "5.0"
tokio = { version = "1", features = ["full"] }

chrono = "0.4"
whoami = "2.1"
argon2 = "0.5.3"
