[package]
name = "tauri-plugin-folder-tree"
version = "0.1.0"
edition = "2021"
links = "tauri-plugin-folder-tree"

[lib]
name = "tauri_plugin_folder_tree"
crate-type = ["rlib", "cdylib"]

[dependencies]
tauri = { version = "2", default-features = false }
serde = { version = "1", features = ["derive"] }

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }
